name: Build Metabase DuckDB Driver

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Metabase repository
      uses: actions/checkout@v4
      with:
        repository: metabase/metabase
        path: metabase
        
    - name: Checkout driver code
      uses: actions/checkout@v4
      with:
        path: metabase/modules/drivers/duckdb
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        
    - name: Install Yarn 1.x
      run: |
        npm install -g yarn@1
        yarn --version
        
    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@12.3
      with:
        cli: latest
        
    - name: Build driver
      working-directory: ./metabase
      run: |
        git apply ./modules/drivers/duckdb/ci/metabase_drivers_deps.patch
        chmod +x ./bin/build-driver.sh
        ./bin/build-driver.sh duckdb
        
    - name: Run integration tests
      working-directory: ./metabase
      run: |
        git apply ./modules/drivers/duckdb/ci/metabase_test_deps.patch
        DRIVERS=duckdb clojure -X:dev:drivers:drivers-dev:ee:ee-dev:test
        
    - name: Upload driver artifact
      uses: actions/upload-artifact@v4
      with:
        name: metabase-duckdb-driver
        path: metabase/resources/modules/duckdb.metabase-driver.jar
        if-no-files-found: error